# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: osadebec98@gmail.com
author_name: Ceejay
contract_name: realitycheck_issuance
deployment_language: python
preset_name: starter
project_name: realitycheck

